package com.hospital.entities;

public enum Specialization {



 Allergist(1),
 Anaesthesiologist(2),
 Andrologist(3),
 Cardiologist(4),
 CardiacElectrophysiologist(5),
 Dermatologist(6),
 EmergencyRoomDoctors(7),
 Endocrinologist(8),
 Epidemiologist(9),
 FamilyMedicinePhysician(10),
 Gastroenterologist(11),
 Geriatrician(12),
 HyperbaricPhysician(13),
 Hematologist(14),
 Hepatologist(15),
 InfectiousDiseaseSpecialist(16),
 Intensivist(17),
 InternalMedicineSpecialist(18),
 MedicalExaminer(19),
 MedicalGeneticist(20),
 Neonatologist(21),
 Nephrologist(22),
 Neurologist(23),
 Neurosurgeon(24),
 NuclearMedicineSpecialist(25),
 Gynecologist(26),
 Oncologist(27),
 Ophthalmologist(28),
 rthopedist(29),
 Otolaryngologist(30),
 Parasitologist(31),
 Pathologist(32),
 Perinatologist(33),
 Periodontist(34),
 Pediatrician(35),
 Physiatrist(36),
 PlasticSurgeon(37),
 Psychiatrist(38),
 Pulmonologist(39),
 Radiologist(40),
 Rheumatologist(41),
 SleepDoctor(42),
 SpinalCordInjurySpecialist(43),
 SportsMedicineSpecialist(44),
 Surgeon(45),
 ThoracicSurgeon(46),
 Urologist(47),
 VascularSurgeon(48),
 Veterinarian(49),
 Acupuncturist(50),
 Audiologist(51),
 AyurvedicPractioner(52),
 Chiropractor(53),
 Diagnostician(54),
 HomeopathicDoctor(55),
 Microbiologist(56),
 NaturopathicDoctor(57),
 PalliativeCareSpecialist(58),
 Pharmacist(59),
 Physiotherapist(60),
 Podiatrist(61),
 RegisteredMassageTherapist(62);

   private int specialization;

   Specialization(int specialization) {
      this.specialization = specialization;
   }
}
